### ISSUE TITLE
Feature request: JSON/CSV export

### ISSUE THREAD

**Issue by todrobbins** [glaurent/MessagesHistoryBrowser#1]
Could you add support for JSON and CSV export? This would be super helpful for utilizing the messages archive. Cheers!

**Comment by glaurent** [comment]
I was considering it, but didn't do it as I wanted to keep the app very basic and I doubted anyone would actually need it. I'll get around it after I've updated it to Swift 3 (which won't be before a little while, sorry).

**Comment by todrobbins** [comment]
Sounds reasonable. Thanks for the comment!

**Comment by glaurent** [comment]
You're welcome :)

**Comment by glaurent** [comment]
Took me long enough, but export to JSON (sorry, not CSV) is now in master.

**Comment by todrobbins** [comment]
Thank you @glaurent! JSON output will be very useful!

**Comment by glaurent** [comment]
You're welcome - please give it a try and tell me if the format suits your needs.
