### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kiliankoe** [glaurent/MessagesHistoryBrowser#3]
Hi!

I remember using your app sometime around a year back or so and am currently trying to access some old chat data, so it seemed like a perfect fit 😊 

Unfortunately the current build seems to crash on startup. I'm trying to run it on the current beta of macOS 10.14 ***and*** with iMessage in iCloud activated, which probably doesn't result in an ideal environment for running this 😅 

I've tried building from source and it crashes on the following line with `Fatal error: Unexpectedly found nil while unwrapping an Optional value`.

https://github.com/glaurent/MessagesHistoryBrowser/blob/ef79e46b54ca9f6474dd073c68a657cb7dc54868/MessagesHistoryBrowser/ChatsDatabase.swift#L108

A quick `po db.scalar(chats.count)` in lldb leads to the same result.

Unfortunately I'm not familiar enough with the APIs you're using to debug this very far. Is there anything I can help to do to resolve this?

**Comment by glaurent** [comment]
Thank you for your report and your offer for help. I haven't tried it yet under macOS 10.14. Did you build it with Xcode 9 or Xcode 10beta ?

Could you try checking the value of chats.count ?

**Comment by kiliankoe** [comment]
I'm currently using Xcode 10 Beta 2. Building with Xcode 9.4 seems to lead to the same result though.

> Could you try checking the value of chats.count ?

Sure, although I'm not sure if the result is very helpful 🙈 
```
▿ ScalarQuery<Int>
  ▿ clauses : QueryClauses
    ▿ select : 2 elements
      - distinct : false
      ▿ columns : 1 element
        ▿ 0 : Expression<Int>
          - template : "count(*)"
          - bindings : 0 elements
    ▿ from : 3 elements
      - name : "chat"
      - alias : nil
      - database : nil
    - join : 0 elements
    - filters : nil
    - group : nil
    - order : 0 elements
    - limit : nil
    - union : 0 elements
```

**Comment by glaurent** [comment]
I've finally been able to reproduce the problem (had a cocoapods issue on my Mojave machine), and the actual issue is that the app can't open the Messages db, due to it being now protected in Mojave (and so the error reporting of my app totally sucks, this case is not really handled at all). I'm not sure how I can get around that, even trying to access the db from the console is locked at the filesystem level (can't chmod the directory). I'll keep investigating...

**Comment by kiliankoe** [comment]
Ah, that totally makes sense. I believe I was prompted to give access on my first run and gave access, not sure though if that made a difference, especially if the app crashes almost instantly.

I haven't had much fun with macOS development, but there must surely be APIs to trigger the user to enable access before trying to actually read anything. Another option would be to (besides the main workflow of the app) not read the DB on startup, but ask the user to do so also giving the option of opening a copy of the db from another location (assuming the directory is causing the permission, not a flag on the file itself). Having copied it elsewhere also allowed me to run a quick python script gathering the data I was looking for.

**Comment by glaurent** [comment]
That's weird, I wasn't prompted at all.

I don't know yet of APIs allowing the app to ask user for access permission. The option of opening it from an other location is likely the simplest one. For what it's worth, you can easily change the path of the DB in the app, it's hardcoded in the ChatsDatabase class (chatsDBPath member). That way you can run the app yourself, until I work around this problem.

**Comment by glaurent** [comment]
I found a fix in the WWDC 2018 session "your apps and the future of macOS security" : in the Security->Privacy panel of the System Preferences, add MessagesHistoryBrowser to the "Application Data" section. The app should work properly afterwards, but I still need to add a proper error reporting about that.
<img width="780" alt="screenshot 2018-07-22 at 12 57 17" src="https://user-images.githubusercontent.com/1167407/43044960-e25d6b50-8daf-11e8-98c3-645aa6e121d3.png">

**Comment by kiliankoe** [comment]
Super cool, thank you!

**Comment by glaurent** [comment]
I've released a new version with several fixes for performance improvement in import and Mojave support, you might want to check out the updated code.
