### ISSUE TITLE
Not importing all chats

### ISSUE THREAD

**Issue by ghost** [glaurent/MessagesHistoryBrowser#4]
Hi,

Only about 10 of contacts are showing as imported, however, I have over 100 chats with people. I am in  High Sierra 10.13.16

**Comment by glaurent** [comment]
I take it you have more than 10 contacts ? What happens if you toggle the "Display Unknown Contacts" item in the View menu ?

**Comment by glaurent** [comment]
Any update on this one ? Could you check the last version of the app ?

**Comment by glaurent** [comment]
closing for lack of reply from user
