### ISSUE TITLE
Unable to show messages?

### ISSUE THREAD

**Issue by jay0221** [glaurent/MessagesHistoryBrowser#5]
I just downloaded this app and I'm not sure if the messages are supposed to appear? The contacts list is blank and I even checked the "display unknown contacts" and yet, nothing. I tried to refresh it, but it says 0% complete and 0 out 10 for almost fifteen minutes now. Is there any way for this to be fixed?

**Comment by glaurent** [comment]
I encountered the same problem recently when working on the app. It's a permission issue, for some reason the contacts helper is stuck even though it should either have permission to access contacts or macOS should show a dialog requesting for permission to access them. I may be missing something, though. Can you check in the Privacy section of your system settings if the app has permission to access both contacts and full disk ?

**Comment by glaurent** [comment]
Could you check the new version 1.6 ? It should fix the problem.

**Comment by glaurent** [comment]
closing for lack of reply from user
