### ISSUE TITLE
Full Disk Access required even though it has been granted?

### ISSUE THREAD

**Issue by mrnoisytiger** [glaurent/MessagesHistoryBrowser#6]
I have enabled Full Disk Access for the app:

<img width="668" alt="screen shot 2018-12-31 at 5 11 45 pm" src="https://user-images.githubusercontent.com/12619586/50569640-2789cb80-0d1f-11e9-8e7b-a22e3e31ab74.png">

When launching the app, it tells me to select the Messages archive, so I pointed it to ~/Library/Messages/Archive and clicked Open. The app then shows:

<img width="554" alt="screen shot 2018-12-31 at 5 12 51 pm" src="https://user-images.githubusercontent.com/12619586/50569649-5011c580-0d1f-11e9-8120-62e94f24fea0.png">

I am on MacOS 10.14 Mojave.

**Comment by glaurent** [comment]
Did you have a previous version of the app installed ? I experienced problems with the Full Disk Access permissions that were apparently due to that.

**Comment by glaurent** [comment]
I found the issue, I'm about to release a v1.7 which should fix it.

**Comment by glaurent** [comment]
v1.7.1 is released, can you confirm if it works for you ? (1.7 had an entitlement issue)

**Comment by mrnoisytiger** [comment]
Yes that has fixed the issue! Thank you so much!

**Comment by glaurent** [comment]
You're welcome, thank you for your help :). For the record you can remove it from the Full Disk Access list, it no longer requires them.
